--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2023. 03. 02. 13:03:43
-- Server version: 5.5.5-10.1.38-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE szamlalo;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Drop table `recepititem`
--
DROP TABLE IF EXISTS recepititem;

--
-- Drop table `products`
--
DROP TABLE IF EXISTS products;

--
-- Drop table `recepithead`
--
DROP TABLE IF EXISTS recepithead;

--
-- Drop table `buyers`
--
DROP TABLE IF EXISTS buyers;

--
-- Drop table `owner`
--
DROP TABLE IF EXISTS owner;

--
-- Set default database
--
USE szamlalo;

--
-- Create table `owner`
--
CREATE TABLE owner (
  id INT(11) NOT NULL AUTO_INCREMENT,
  companyName VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `buyers`
--
CREATE TABLE buyers (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) DEFAULT NULL,
  postalCode INT(11) DEFAULT NULL,
  settlement VARCHAR(255) DEFAULT NULL,
  streetAddress VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `recepithead`
--
CREATE TABLE recepithead (
  id INT(11) NOT NULL AUTO_INCREMENT,
  accountNumber INT(11) DEFAULT NULL,
  kelt VARCHAR(255) DEFAULT NULL,
  fulllfillment VARCHAR(255) DEFAULT NULL,
  buyerId INT(11) DEFAULT NULL,
  ownerId INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE recepithead 
  ADD CONSTRAINT FK_recepithead_owner_id FOREIGN KEY (ownerId)
    REFERENCES owner(id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE recepithead 
  ADD CONSTRAINT FK_szamlafej_vevok_id FOREIGN KEY (buyerId)
    REFERENCES buyers(id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `products`
--
CREATE TABLE products (
  id INT(11) NOT NULL AUTO_INCREMENT,
  productName VARCHAR(255) DEFAULT NULL,
  price INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 51,
AVG_ROW_LENGTH = 327,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `recepititem`
--
CREATE TABLE recepititem (
  id INT(11) NOT NULL AUTO_INCREMENT,
  recepitHeadId INT(11) DEFAULT NULL,
  productId INT(11) DEFAULT NULL,
  quantity INT(11) DEFAULT NULL,
  quantityUnit VARCHAR(255) DEFAULT NULL,
  grossUnit INT(11) DEFAULT NULL,
  vatPercentage INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE recepititem 
  ADD CONSTRAINT FK_szamlatetel_szamlafej_id FOREIGN KEY (recepitHeadId)
    REFERENCES recepithead(id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE recepititem 
  ADD CONSTRAINT FK_szamlatetel_termekek_id FOREIGN KEY (productId)
    REFERENCES products(id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `users`
--
CREATE TABLE users (
  id INT(11) NOT NULL AUTO_INCREMENT,
  firstName VARCHAR(255) DEFAULT NULL,
  lastName VARCHAR(255) DEFAULT NULL,
  gender VARCHAR(255) DEFAULT NULL,
  userName VARCHAR(255) DEFAULT NULL,
  email VARCHAR(50) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  number INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

-- 
-- Dumping data for table owner
--
-- Table szamlalo.owner does not contain any data (it is empty)

-- 
-- Dumping data for table buyers
--
INSERT INTO buyers VALUES
(1, 'Kovacs Roland', 5000, 'Szolnok', 'Sziget utca 4'),
(2, 'Nagy Ibolya', 1051, 'Budapest', 'Nefelejcs ut 7'),
(3, 'Ady Endre', 1051, 'Budapest', 'Fortuna utca 16'),
(4, 'Kossuth Andras', 5100, 'Jaszbereny', 'Sulloi ut 1'),
(5, 'Rakoczy Peter', 2740, 'Abony', 'Prohaszka utca 10');

-- 
-- Dumping data for table recepithead
--
-- Table szamlalo.recepithead does not contain any data (it is empty)

-- 
-- Dumping data for table products
--
INSERT INTO products VALUES
(1, 'Celestron NexStar Evolution 9.25"', 6432),
(2, 'Celestron Inspire 100AZ Refractor', 2345),
(3, 'Celestron Astro Fi 102', 586),
(4, 'Celestron NexStar 5SE', 8890),
(5, 'Celestron NexStar 4SE', 544),
(6, 'Celestron StarSense Explorer LT 114AZ', 2269),
(7, 'Celestron NexStar Evolution 9.25', 2840),
(8, 'Celestron NexStar Evolution 6', 179),
(9, 'Celestron NexStar Evolution 8', 219),
(10, 'Celestron AstroFi 130/650 Newton', 359),
(11, '130/900 SkyWatcher Explorer-130 Newton EQ2', 365),
(12, 'SkyWatcher Virtuoso Gti 130/650 Dobson', 894),
(13, 'Celestron CPC Deluxe 1100 HD', 5098),
(14, 'Celestron NexStar Evolution 9.25"', 2570),
(15, 'Celestron Inspire 100AZ Refractor', 267),
(16, 'Celestron Astro Fi 102', 585),
(17, 'Celestron NexStar 5SE', 840),
(18, 'Celestron NexStar 4SE', 543),
(19, 'Celestron StarSense Explorer LT 114AZ', 219),
(20, 'Celestron NexStar Evolution B 9.25', 2840),
(21, 'Celestron NexStar Evolution B 6', 16125),
(22, 'Celestron NexStar Evolution B 8', 2142),
(23, 'Celestron AstroFi 130/650 Newton B', 300),
(24, '130/900 SkyWatcher Explorer-130 Newton EQ2B', 325),
(25, 'SkyWatcher Virtuoso Gti 130/650 Dobson B', 394),
(26, 'Celestron CPC Deluxe 1100 HD B', 50939),
(27, 'Celestron NexStar Evolution A 9.25 C"', 23550),
(28, 'Celestron Inspire 100AZ Refractor D', 2237),
(29, 'Celestron Astro Fi 102 G', 5827),
(30, 'Celestron NexStar 5SE G', 8001),
(31, 'Celestron NexStar 4SE G', 5446),
(32, 'Celestron StarSense Explorer LTA 114AZG', 2296),
(33, 'Celestron NexStar Evolution 9.25 AG', 28408),
(34, 'Celestron NexStar Evolution 6 C', 16795),
(35, 'Celestron NexStar Evolution 8 AC', 21997),
(36, 'Celestron AstroFi 130/650 Newton C', 6895),
(37, '130/900 SkyWatcher Explorer-130 Newton EQ2 C', 3645),
(38, 'SkyWatcher Virtuoso Gti 130/650 Dobson C', 3943),
(39, 'Celestron CPC Deluxe 1100 HD C', 509),
(40, 'Celestron NexStar Evolution 9.25 C"', 2370),
(41, 'Celestron Inspire 100AZ Refractor S', 2270),
(42, 'Celestron Astro Fi 102 C', 5873),
(43, 'Celestron NexStar 5SE E', 800),
(44, 'Celestron NexStar 4SE E', 544),
(45, 'Celestron StarSense Explorer LT 114AZ U', 2029),
(46, 'Celestron NexStar Evolutionb 9.25 U', 28403),
(47, 'Celestron NexStar Evolution 6 U', 167924),
(48, 'Celestron NexStar Evolution 8 U', 219932),
(49, 'Celestron AstroFi 130/650 Newton U', 68914),
(50, '130/900 SkyWatcher Explorer-130 Newton EQ2 U', 33265);

-- 
-- Dumping data for table users
--
-- Table szamlalo.users does not contain any data (it is empty)

-- 
-- Dumping data for table recepititem
--
-- Table szamlalo.recepititem does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;